test: 
  test_mode: true
  gateway:   bogus

development: 
  test_mode:  true
  gateway:    paypal
  :login:     bob_biz_api1.domain.com
  :password:  asc123
  :signature: Qwerty1234567890

production: 
  test_mode:  false
  gateway:    paypal
  :login:     real_person.domain.com
  :password:  real_password
  :signature: real_signature
